### ISSUE TITLE
Some checklist

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/wp-database-backup#46]
- [x] Loader and message should come below create backup button
- [x] html tags are coming in string
- [x] Classes and ID must have prefix
- [x] Add a caption in download history table like this https://prnt.sc/P9_OWc0OHprR
- [x] Create fullback should be process internally using any cron job and show progress bar
- [x] Add InProcess section to see pending backup

**Comment by akshaywali** [comment]
Pushed in update 6.3
